package com.rosettastone.succor
import com.rosettastone.succor.drools.Item;
global com.rosettastone.succor.drools.ItemService itemService

rule "Equal rule 4"
when
    $item: Item(price == 8)
then
    itemService.equal($item, 4);
end

rule "Equal rule 5"
when
    $item: Item(price == 10)
then
    itemService.equal($item, 5);
end

rule "Equal rule 6"
when
    $item: Item(price == 12)
then
    itemService.equal($item, 6);
end
